version: 2
jobs:
  build:
    working_directory: ~/pkcs11
    docker:
      - image: circleci/ubuntu-server:latest
        environment:
          CI: cicleci
          POSTGRES_DB: circle_test
          CC: clang
    branches:
      only:
        - master
        - Circle-CI-Support
    steps:
      - run:
          name: "refresh"
          command: |
            sudo apt-get update ; wait ;
      - run:
          name: "install dependencies"
          command: |
            sudo apt-get -y install build-essential libssl-dev openssl libnss3 libnss3-dev libtool clang autotools-dev automake make autoconf ; wait ;
      - run:
          name: "build dependencies"
          command: |
            sudo apt-get -y --compile source ubuntu-toolchain-r-test || true
      - checkout
      - run:
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || true
      - run:
          shell: /bin/bash
          name: "Tests"
          command: |
            .circleci/run_ci.sh
destination: build
